wiringx-git: Bump to latest upstream r240.4e620afa05a5 and enable aarch64
Bumping to r240.4e620afa05a5 fixes missing dependency to orangepipc2Init
when using Python:

    $ python
    from wiringX import gpio
    ImportError: /usr/lib/python3.6/site-packages/wiringX/gpio.cpython-36m-aarch64-linux-gnu.so: undefined symbol: orangepipc2Init

Signed-off-by: Krzysztof Kozlowski <krzk@kernel.org>